Name: Nur Aufa Student ID : 1101220508

In [28]:
import pandas as pd

In [30]:
kl = pd.read_excel(r"List Customer Call.xlsx")
kl

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [32]:
kl = kl.drop_duplicates()
kl

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [34]:
kl = kl.drop(columns = "Not_Useful_Column")
kl

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [41]:
kl["Last_Name"] = kl["Last_Name"].str.strip("abc")
kl

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

menghapus kolom pada Last Name

In [46]:
import re
# Mengganti NaN dengan string kosong
kl["Phone_Number"] = kl["Phone_Number"].fillna('')
# Mengganti 'nan--', 'Na--', dan 'n/a' dengan string kosong menggunakan regex
kl["Phone_Number"] = kl["Phone_Number"].replace(r'nan--|Na--|n/a', '', regex=True)
# Menggunakan regex untuk menghapus semua karakter non-angka
kl["Phone_Number"] = kl["Phone_Number"].replace(r'[^0-9]', '', regex=True)
kl

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,1235455421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,1236439775,93 West Main Street,No,Yes
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,1235432345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,8766783469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,3047622467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,,1209 South Street,No,No
7,1008,Sherlock,Holmes,8766783469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,1235455421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,1235432345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,8766783469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,3047622467,214 HR Avenue,N,No
15,1016,Ron,Weasley,1235455421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,1236439775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,,N/a,N/a,Yes
19,1020,Anakin,Skywalker,8766783469,"910 Tatooine Road, Tatooine",Yes,N

menggunakan fungsi apply dan lambda untuk membagi string berdasarkan koma

In [49]:
kl[['Street_Address', 'State', 'Zip_Code']] = kl['Address'].apply(lambda x: pd.Series(x.split(',', 2)))
kl

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,1235455421,"123 Shire Lane, Shire",Yes,No,123 Shire Lane,Shire,NaN
1,1002,Abed,Nadir,1236439775,93 West Main Street,No,Yes,93 West Main Street,NaN,NaN
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN,298 Drugs Driveway,NaN,NaN
3,1004,Dwight,Schrute,1235432345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,8766783469,123 Dragons Road,Y,No,123 Dragons Road,NaN,NaN
5,1006,Ron,Swanson,3047622467,768 City Parkway,Yes,Yes,768 City Parkway,NaN,NaN
6,1007,Jeff,Winger,,1209 South Street,No,No,1209 South Street,NaN,NaN
7,1008,Sherlock,Holmes,8766783469,98 Clue Drive,N,No,98 Clue Drive,NaN,NaN
8,1009,Gandalf,NaN,,123 Middle Earth,Yes,NaN,123 Middle Earth,NaN,NaN
9,1010,Peter,Parker,1235455421,"25th Main Street, New York",Yes,No,25th Main Street,New York,NaN
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,No,612 Shire Lane,Shire,NaN
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,2394 Hogwarts Avenue,NaN,NaN
12,1013,Don,Draper,1235432345,2039 Main Street,Yes,N,2039 Main Street,NaN,NaN
13,1014,Leslie,Knope,8766783469,343 City Parkway,Yes,No,343 City Parkway,NaN,NaN
14,1015,Toby,Flenderson,3047622467,214 HR Avenue,N,No,214 HR Avenue,NaN,NaN
15,1016,Ron,Weasley,1235455421,2395 Hogwarts Avenue,No,N,2395 Hogwarts Avenue,NaN,NaN
16,1017,Michael,Scott,1236439775,"121 Paper Avenue, Pennsylvania",Yes,No,121 Paper Avenue,Pennsylvania,NaN
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,3498 Super Lane,NaN,NaN
18,1019,Creed,Braton,,N/a,N/a,Yes,N/a,NaN,NaN
19,1020,Anakin,Skywalker,8766783469,"910 Tatooine Road, Tatooine",Yes,N,910 Tatooine Road,Tatooine,NaN

menggunakan fungsi .map() untuk mengganti nilai 'Yes' dan 'No' menjadi 'Y' dan 'N'

In [52]:
kl["Do_Not_Contact"] = kl["Do_Not_Contact"].map({'Yes': 'Y', 'No': 'N'}).fillna(kl["Do_Not_Contact"])
kl["Paying Customer"] = kl["Paying Customer"].map({'Yes': 'Y', 'No': 'N'}).fillna(kl["Paying Customer"])
kl

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,1235455421,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,NaN
1,1002,Abed,Nadir,1236439775,93 West Main Street,N,Y,93 West Main Street,NaN,NaN
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN,298 Drugs Driveway,NaN,NaN
3,1004,Dwight,Schrute,1235432345,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,8766783469,123 Dragons Road,Y,N,123 Dragons Road,NaN,NaN
5,1006,Ron,Swanson,3047622467,768 City Parkway,Y,Y,768 City Parkway,NaN,NaN
6,1007,Jeff,Winger,,1209 South Street,N,N,1209 South Street,NaN,NaN
7,1008,Sherlock,Holmes,8766783469,98 Clue Drive,N,N,98 Clue Drive,NaN,NaN
8,1009,Gandalf,NaN,,123 Middle Earth,Y,NaN,123 Middle Earth,NaN,NaN
9,1010,Peter,Parker,1235455421,"25th Main Street, New York",Y,N,25th Main Street,New York,NaN
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Y,N,612 Shire Lane,Shire,NaN
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,2394 Hogwarts Avenue,NaN,NaN
12,1013,Don,Draper,1235432345,2039 Main Street,Y,N,2039 Main Street,NaN,NaN
13,1014,Leslie,Knope,8766783469,343 City Parkway,Y,N,343 City Parkway,NaN,NaN
14,1015,Toby,Flenderson,3047622467,214 HR Avenue,N,N,214 HR Avenue,NaN,NaN
15,1016,Ron,Weasley,1235455421,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,NaN,NaN
16,1017,Michael,Scott,1236439775,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,NaN
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,3498 Super Lane,NaN,NaN
18,1019,Creed,Braton,,N/a,N/a,Y,N/a,NaN,NaN
19,1020,Anakin,Skywalker,8766783469,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,NaN

In [54]:
kl = kl.fillna('')
kl

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,1235455421,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,
1,1002,Abed,Nadir,1236439775,93 West Main Street,N,Y,93 West Main Street,,
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,,298 Drugs Driveway,,
3,1004,Dwight,Schrute,1235432345,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,8766783469,123 Dragons Road,Y,N,123 Dragons Road,,
5,1006,Ron,Swanson,3047622467,768 City Parkway,Y,Y,768 City Parkway,,
6,1007,Jeff,Winger,,1209 South Street,N,N,1209 South Street,,
7,1008,Sherlock,Holmes,8766783469,98 Clue Drive,N,N,98 Clue Drive,,
8,1009,Gandalf,,,123 Middle Earth,Y,,123 Middle Earth,,
9,1010,Peter,Parker,1235455421,"25th Main Street, New York",Y,N,25th Main Street,New York,
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Y,N,612 Shire Lane,Shire,
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,,2394 Hogwarts Avenue,,
12,1013,Don,Draper,1235432345,2039 Main Street,Y,N,2039 Main Street,,
13,1014,Leslie,Knope,8766783469,343 City Parkway,Y,N,343 City Parkway,,
14,1015,Toby,Flenderson,3047622467,214 HR Avenue,N,N,214 HR Avenue,,
15,1016,Ron,Weasley,1235455421,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,1236439775,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,,3498 Super Lane,,
18,1019,Creed,Braton,,N/a,N/a,Y,N/a,,
19,1020,Anakin,Skywalker,8766783469,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,

menggunakan .loc untuk mengganti nilai 'N/a' dengan string kosong

In [61]:
kl = kl.replace('N/a'," ")
kl

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,1235455421,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,
1,1002,Abed,Nadir,1236439775,93 West Main Street,N,Y,93 West Main Street,,
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,,298 Drugs Driveway,,
3,1004,Dwight,Schrute,1235432345,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,8766783469,123 Dragons Road,Y,N,123 Dragons Road,,
5,1006,Ron,Swanson,3047622467,768 City Parkway,Y,Y,768 City Parkway,,
6,1007,Jeff,Winger,,1209 South Street,N,N,1209 South Street,,
7,1008,Sherlock,Holmes,8766783469,98 Clue Drive,N,N,98 Clue Drive,,
8,1009,Gandalf,,,123 Middle Earth,Y,,123 Middle Earth,,
9,1010,Peter,Parker,1235455421,"25th Main Street, New York",Y,N,25th Main Street,New York,
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Y,N,612 Shire Lane,Shire,
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,,2394 Hogwarts Avenue,,
12,1013,Don,Draper,1235432345,2039 Main Street,Y,N,2039 Main Street,,
13,1014,Leslie,Knope,8766783469,343 City Parkway,Y,N,343 City Parkway,,
14,1015,Toby,Flenderson,3047622467,214 HR Avenue,N,N,214 HR Avenue,,
15,1016,Ron,Weasley,1235455421,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,1236439775,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,,3498 Super Lane,,
18,1019,Creed,Braton,,,,Y,,,
19,1020,Anakin,Skywalker,8766783469,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,

menghapus baris yang memiliki nilai 'Y' pada kolom 'Do_Not_Contact' menggunakan kondisi boolean

In [64]:
kl = kl[kl["Do_Not_Contact"] != 'Y']
kl

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,1235455421,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,,298 Drugs Driveway,,
4,1005,Jon,Snow,8766783469,123 Dragons Road,Y,N,123 Dragons Road,,
6,1007,Jeff,Winger,,1209 South Street,N,N,1209 South Street,,
7,1008,Sherlock,Holmes,8766783469,98 Clue Drive,N,N,98 Clue Drive,,
8,1009,Gandalf,,,123 Middle Earth,Y,,123 Middle Earth,,
9,1010,Peter,Parker,1235455421,"25th Main Street, New York",Y,N,25th Main Street,New York,
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Y,N,612 Shire Lane,Shire,
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,,2394 Hogwarts Avenue,,
12,1013,Don,Draper,1235432345,2039 Main Street,Y,N,2039 Main Street,,
13,1014,Leslie,Knope,8766783469,343 City Parkway,Y,N,343 City Parkway,,
14,1015,Toby,Flenderson,3047622467,214 HR Avenue,N,N,214 HR Avenue,,
15,1016,Ron,Weasley,1235455421,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,1236439775,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,,3498 Super Lane,,
19,1020,Anakin,Skywalker,8766783469,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,

menghapus baris yang memiliki nilai kosong pada kolom 'Phone_Number'